name: spikegadgets_to_nwb
channels:
- defaults
- conda-forge
- franklab
dependencies:
- numpy
- scipy
- pandas
- pynwb
- ipython
- black
- pytest
- pytest-cov
- pip
- pyyaml
- ffmpeg
- dask
- pip:
    - ndx-franklab-novela
    - neo
    - hdmf=3.8.1