name: trodes_to_nwb
channels:
- conda-forge
- franklab
dependencies:
- jsonschema=4.19.2
- numpy
- scipy
- pandas
- pynwb
- nwbinspector
- dask
- ipython
- black
- pytest
- pytest-cov
- pytest-mock
- pyyaml
- ffmpeg
- pip
- pip:
    - ndx-franklab-novela
    - neo
