name: spikegadgets_to_nwb
channels:
- defaults
- conda-forge
- franklab
dependencies:
- numpy
- scipy
- pandas
- pynwb
- hdmf
- nwbinspector
- dask
- ipython
- black
- pytest
- pytest-cov
- pip
- pyyaml
- jsonschema
- ffmpeg
- pip:
    - ndx-franklab-novela
    - neo
