name: spikegadgets_to_nwb
channels:
- defaults
- conda-forge
- franklab
dependencies:
- numpy
- scipy
- pandas
- pynwb
- ipython
- black
- pytest
- pytest-cov
- pip
- pyyaml
- jsonschema
- pip:
    - ndx-franklab-novela